{% set version = "3.0.8a" %}
{% set release_flag = false %}

package:
    name: gorgon
    version: {{ version }}

source:
    git_url: https://github.com/GorgonCryoEM/Gorgon.git
{%- if release_flag %}
    git_tag: release/v{{ version }}
{% else %}
    git_tag: v{{ version }}
{% endif %}

build:
    number: 0

requirements:
    build:
        - cmake >=3.4
        - python 2.7.*
        - boost
        - fftw
        - freeglut  # [not osx]
        - setuptools
        - toolchain  # [not win]
    run:
        - python 2.7.*
        - boost
        - fftw
        - freeglut  # [not osx]
        - termcolor
        - pyqt
        - pyopengl

test:                                                         # [not win]
  source_files:                                               # [not win]
    - tests                                                   # [not win]
    - demo/groel                                              # [not win]
  requires:                                                   # [not win]
    - nose                                                    # [not win]
    - docutils                                                # [not win]
  commands:                                                   # [not win]
    - nosetests --with-doctest --doctest-tests -s -vv         # [not win]

about:
  summary: Gorgon, an interactive molecular modeling system
  home:  http://gorgon.wustl.edu
  license_file: LICENSE.txt
  description: |
    Gorgon is an interactive molecular modeling system 
    specifically geared towards cryo-EM and other low resolution 
    structures of macromolecular complexes. The long term goal of 
    the gorgon project is to be able to address to every part of 
    the molecular modeling pipeline starting from the initial 
    volumetric reconstruction of the complex all the way to the 
    final placement of each individual atom.
  dev_url: https://github.com/GorgonCryoEM/Gorgon
